### ISSUE TITLE
web server error 

### ISSUE THREAD

**Issue by bio-rat** [tiejundong/FlexPose#1]
The web server only works when I use the provided input example but as soon as I use my protein and ligand it shows this error.

"FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpdlk2psln/structure_output_path/0.pdb'
Traceback:
File "/data/lab_website/.conda/envs/streamlit/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/data/lab_website/lab_website_code/pages/1_FlexPose.py", line 141, in <module>
    view.addModel(grep_pdb_rename_chain(f'{structure_output_path}/0.pdb', 'ATOM', 'A'), 'pdb')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/lab_website/lab_website_code/pages/1_FlexPose.py", line 132, in grep_pdb_rename_chain
    lines = open(pdb_path, 'r').readlines()
            ^^^^^^^^^^^^^^^^^^^

**Comment by tiejundong** [comment]
The visualization failed. You need to download the output file and visualize it locally. If there are no downloadable files, please re-check your inputs. Please ensure that the input formats are as similar to the PDBbind dataset as possible.

**Comment by bio-rat** [comment]
[prediction (1).zip](https://github.com/tiejundong/FlexPose/files/13326041/prediction.1.zip)
This time I was able to run it. Showed no error but no visualization. This is the output file. Only 490B and empty.

**Comment by tiejundong** [comment]
It seems that your inputs did not pass the preprocessing steps and, therefore, no outputs. Please ensure the ligand file can be read by rdkit, the protein file can be read by modeller and Rosetta, and each input file contains only one conformation. Ligand has less than 150 heavy atoms. If possible, you can upload inputs here for further debugging.

**Comment by bio-rat** [comment]
[biorat_input.zip](https://github.com/tiejundong/FlexPose/files/13326874/biorat_input.zip)
Here's mine input files. Could not think of any reason that it doesn't work

**Comment by tiejundong** [comment]
Your input format is correct. However, there is no pocket selection file, and the input ligand is located far from the receptor (>20Å). If you use the input ligand for pocket selection, no protein residues are selected. Here is a file for pocket selection as your reference, which is derived from 8DQH. Besides, FlexPose focuses on the local docking task. If you want to perform global docking, you may use other models like DiffDock or other methods to predict pocket.
[inputs.zip](https://github.com/tiejundong/FlexPose/files/13327557/inputs.zip)

**Comment by bio-rat** [comment]
Thank you so much it works for me now. How did you extract the ligand with coordinates like that?

**Comment by tiejundong** [comment]
You can use pymol or VMD
