### ISSUE TITLE
Using FlexPose to dock proteins with non-natural amino acids.

### ISSUE THREAD

**Issue by liyue9129** [tiejundong/FlexPose#10]
Hi ！
Thank you for your amazing work！
I'm trying to use FlexPose to dock proteins with non-natural amino acids（like CME...）, but I encountered the following error:
![image](https://github.com/user-attachments/assets/5d1d5066-7785-4547-8a1b-fc9efd895040)
This error occurred in the code highlighted in the red box.
![image](https://github.com/user-attachments/assets/cec95233-5fba-4265-a74c-e5d0033327e2)

The following is the protein-ligand complex file that caused this error：
[8CNH_V6U.zip](https://github.com/user-attachments/files/17585164/8CNH_V6U.zip)

How can I make FlexPose work in this case? 
Additionally, I found some parameter files for amino acids in the residue_types directory. May I ask how these parameter files were generated?
![image](https://github.com/user-attachments/assets/9a7acebf-0a3c-4e56-99d9-5bb682385faf)

Thank you!

**Comment by tiejundong** [comment]
Thank you for your attention to our work.
1. Non-natural amino acids are not considered in the current version of FlexPose. If the non-natural residue is located far from the binding pocket, you may consider using a homologous structure as an alternative.
2. These parameter files are derived from Rosetta and are used to conduct side-chain torsion calculations in FlexPose. Detailed descriptions can be found in the Rosetta documentation.

**Comment by liyue9129** [comment]
Thank you for your help！
