### ISSUE TITLE
The trained model

### ISSUE THREAD

**Issue by Zhang-Runze** [tiejundong/FlexPose#2]
Great job! 
But we would like to use this method locally. Could you provide the trained model? Thank you very much!

**Comment by tiejundong** [comment]
Thanks for your attention to our work. 

After installation, `FlexPose.utils.prediction` loads parameters automatically, or you can download parameters manually [here](http://www.knightofnight.com/upload/data/FlexPose/FlexPose_param.chk).

**Comment by Zhang-Runze** [comment]
Thank you for your very efficient response！
