### ISSUE TITLE
About pretraining code

### ISSUE THREAD

**Issue by twopin** [tiejundong/FlexPose#3]
Hi, your work is really good and solid!  I'm wondering if you can upload your pretraining scripts for protein and ligand encoders? I think your pretraining tasks are quite interesting and informative. Thank you so much!

**Comment by tiejundong** [comment]
Thanks for your attention to our work.

Scripts relative to pretraining were updated. `train/pretrain_protein.py`, `train/pretrain_ligand.py`, `model/layers.py`, `utils/pocket_data.py`, and `utils/ligand_data.py`

**Comment by twopin** [comment]
Thank you so much for your quick response:)
