### ISSUE TITLE
errors when running demo.py

### ISSUE THREAD

**Issue by zaixizhang** [tiejundong/FlexPose#4]
Hi,

Thanks for your brilliant work and code! I encountered an error when running demo.py:
<img width="1134" alt="image" src="https://github.com/tiejundong/FlexPose/assets/52197241/4e33ec53-8fe9-4a8b-a4ae-1ac87319ac1b">
Could you offer some suggestions?

Bests,

**Comment by tiejundong** [comment]
Thanks for your attention to our work. Please set `prepare_data_with_multi_cpu=False` to avoid processing by `ray`.

**Comment by zaixizhang** [comment]
Thanks! It works.
