### ISSUE TITLE
Confused of the training process

### ISSUE THREAD

**Issue by zaixizhang** [tiejundong/FlexPose#5]
Hi Authors,

Thanks for the brilliant work! I am a little confused with the training process, where apo structures, holo-structures, or fake apo structures are randomly selected as input. For flexible binding, is it more intuitive to input apo structures and predict holo-structures in the training process?

Thanks!

**Comment by tiejundong** [comment]
Sorry for unclearly describing the training process. The holo proteins are used as ground truth; inputs can be apo or holo proteins, i.e., the model can predicts holo proteins with apo proteins.
