### ISSUE TITLE
about run demo.py

### ISSUE THREAD

**Issue by xionghaoli** [tiejundong/FlexPose#7]
I installed Flexpose locally and ran the python demo.py without error, but without any file generation. What could be the reason!
![view](https://github.com/tiejundong/FlexPose/assets/154570963/4cf774a2-3300-437b-80d8-5d5cf8e929c6)

**Comment by tiejundong** [comment]
No inputs were successfully preprocessed. As I don't know the exact details of your environment setup, brief guesses as to the possible causes are as follows:

1. Some dependencies were not installed successfully, e.g. no license for the modeller.
2. The locations of input files (e.g. `./FlexPose/example/4r6e/4r6e_protein.pdb`) do not match your working directory.
3. Try to close the `ray` (set `prepare_data_with_multi_cpu` to `False`).
