### ISSUE TITLE
Only the sidechain angles are changled for the output protein

### ISSUE THREAD

**Issue by zaixizhang** [tiejundong/FlexPose#8]
Hi Tiejun,

Thanks for the brilliant work! I took a look at https://github.com/tiejundong/FlexPose/blob/master/FlexPose/utils/prediction.py and find the save_struct function only updates the sidechain angles. Since the alpha carbon coordinates are predicted, have you considered also changing the backbone?

Bests,

**Comment by tiejundong** [comment]
Thanks for your attention to our work. Theoretically, the backbone can also be remodeled with predicted terms by FlexPose (e.g. CA or CB coordinates). However, providing physically plausible backbone structures usually requires energy minimization for entire proteins. In our early testing, the time cost was too high for common tasks (e.g., drug screening), so we left this issue for future research.
