### ISSUE TITLE
About .chk Files Download

### ISSUE THREAD

**Issue by sasaju** [tiejundong/FlexPose#9]
Hi Tiejun,
I noticed that the `.chk` file seems to be uploaded to your personal website, and the download speed is about 150kb/s. Is there any other faster download method? For example, Google Drive or Baidu Cloud Disk.
Thank you.

**Comment by tiejundong** [comment]
Thanks for your attention to our work. 
-You can download parameters [here](https://1drv.ms/u/c/469b767efa9cca5a/EWWl7q0ZtCpEvAHBqyvK5jsBAo109EquswbYq9Z6lkwmWw).

**Comment by sasaju** [comment]
Thanks for your help!
